# Generated by Django 3.1.3 on 2021-01-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210119_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
